# Generated by Django 2.1.3 on 2018-11-24 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('example_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MyLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('log_txt', models.CharField(max_length=255)),
            ],
        ),
        migrations.DeleteModel(
            name='CountUp',
        ),
    ]
